### ISSUE TITLE
chat.privacytools.io / Riot tracking issue

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1049]
## chat.privacytools.io/selfhosted instance issues

*Check boxes as they are fixed on PTIO*

* [ ] Host Dimension instead of relying on vector.im
    * upstream issue letting clients know about it: https://github.com/vector-im/riot-web/issues/6430
        * [x] upstream spec and sdk change allowing this has been merged https://github.com/matrix-org/matrix-doc/pull/1957 & https://github.com/matrix-org/matrix-react-sdk/pull/3340
* [ ] Host identity server ***OR*** set it to chat.privacytools.io (same as homeserver) so it won't work.
    * https://github.com/matrix-org/matrix-doc/blob/6e8739c989172c351a6ead66f073b413f6340326/api/client-server/login.yaml#L147-L148 ?
    * Update 10/7: I don't know if our fix actually works currently so I'm unchecking this box, see: https://github.com/privacytoolsIO/privacytools.io/issues/1049#issuecomment-539269846
* [ ] Host Jitsi Meet
    * upstream: ~~https://github.com/vector-im/riot-web/issues/7711 ***`WONTFIX`***~~ https://github.com/vector-im/riot-web/issues/6930

## Upstream privacy issues

* **[Upstream Privacy Tracker](https://vector-im.github.io/feature-dashboard/#/plan?label=privacy-sprint&repo=vector-im/riot-web&repo=vector-im/riot-ios&repo=vector-im/riot-android&repo=vector-im/riotX-android&repo=matrix-org/matrix-doc&repo=matrix-org/sydent)** which seems to have different priorities and miss some issues below, notably Tor and actually removing removed messages from the database.

### major

Privacy issues that I think prevent PTIO listing:

* matrix-org/matrix-doc#447 - history is stored forever, there is no way to limit how much or how long
    * Signal & Wire: messages aren't stored on server, clients have option how many old messages to keep + both also support disappearing/timed/exploding messages.
* matrix-org/synapse#1263 - uploaded media/files aren't removed when they are removed in Riot
* ~~matrix-org/synapse#1287 - actually removing removed messages from the database~~ fixed
* https://github.com/vector-im/riot-web/issues/7649 / https://github.com/matrix-org/matrix-doc/pull/2134 - private contact discovery
    *I am not sure which topic to put this under, but Signal & Wire both have this.*
* https://github.com/matrix-org/matrix.org/issues/342 - Matrix.org uses Cloudflare (issue closed without disabling Cloudflare)
    * See also https://github.com/privacytoolsIO/privacytools.io/issues/374. I understand this to mean that Cloudflare can one way or another read all traffic going through Matrix.org including IRC users who have never even heard of Matrix if someone happens to use Matrix on the same IRC channel? Matrix.org is quite big compared to an individual Cloudflaring their IRC client, I have heard a number 1500 connections associated with a I-line request from third party bridge admin.
    * Wire and Signal [citation needed] apparently have support pages behind Cloudflare https://github.com/wireapp/wire-webapp/issues/5716.

#### major privacy issues also with selfhosting

I consider these as major due to Cloudflare as the traffic to integration manager and identity server would go through it and so would all messages assuming the user federated with Matrix.org. These may be irrelevant to user who is on Matrix.org.

* https://github.com/vector-im/riot-web/issues/10161 - Store Integration Manager preferences in account data and allow user to change them somewhere sensible
* https://github.com/vector-im/riot-web/issues/10167 - Present an aggregated terms of service dialogue at registration if possible
* https://github.com/vector-im/riot-web/issues/10087 - Prompt to accept integration manager policies on registration
* https://github.com/vector-im/riot-web/issues/10094 - Store identity server in Account Data and support choosing identity server integration in User Settings
* https://github.com/vector-im/riotX-android/issues/20 - Identity server is hardcoded in RiotX (Android client rewrite), the issue is closed and no one has commented on identity server since it was pointed out on 2019-07-09.

### medium

*I need a better word here, but these would be issues that also affect other recommended instant messengers and may not be a blocker.*

* https://github.com/matrix-org/synapse/issues/4565 - metadata resistance
    * to-read for me, is this similar like Wire server knows connections between users, or is this a more serious one?*

### nice to have

* vector-im/riot-web#4426 - riot does not scrub exif data from upload
    * [Discord apparently does](https://github.com/privacytoolsIO/privacytools.io/issues/1049#issuecomment-531200503), [Signal](https://github.com/signalapp/Signal-iOS/pull/2907) and [Wire](https://github.com/wireapp/wire/issues/208) do.
* https://github.com/vector-im/riot-meta/issues/287 - Proxy/Tor support meta issue
    * I cannot find option to enable Tor use either in Signal or Wire, Conversations would have it
    * https://github.com/vector-im/riot-web/issues/3320 - desktop
    * https://github.com/vector-im/riot-android/issues/1234 - Android
    * https://github.com/vector-im/riot-ios/issues/1085 - iOS

### unsorted / note

* matrix-org/synapse#1941 - allow account deletion, not just deactivation
    * I am not sure where exactly to put this either.
* https://github.com/vector-im/riot-web/issues/7757 - Open source the integrations server ***`WONTFIX`***
* https://github.com/vector-im/riot-web/issues/6739 - stickers aren't encrypted
* Less technical users may register on matrix.org unknowingly by default
    * https://github.com/vector-im/riot-ios/issues/2614
    * ~~https://github.com/vector-im/riotX-android/issues/450~~
    * https://github.com/vector-im/riot-android/issues/3238

## Research papers

* [Notes on privacy and data collection of Matrix.org](https://github.com/libremonde-org/paper-research-privacy-matrix.org/blob/master/part1/README.md)
* [Notes on privacy and data collection of Matrix.org, Part 2](https://github.com/libremonde-org/paper-research-privacy-matrix.org/blob/master/part2/README.md)

* * * * *

These issues are mostly took from #840, if you are aware of reported issues that aren't listed here, please do comment them and someone from the team will edit this issue and add them.

I was personally missing a list of things that can be done today to avoid the privacy issues that Matrix/Riot currently has and this may be helpful while considering the delisting (#1047).

**Comment by Mikaela** [comment]
@lampholder Could you also comment on these issues?

**Comment by lampholder** [comment]
Sorry I missed this earlier - I will take a look and come back with responses as soon as I can.

**Comment by lampholder** [comment]
Hi @Mikaela,

Sorry I'm only just getting to this now. Can I check what this list of issues represents to you?

In the interests of providing _some_ hopefully useful feedback now, I'm going to assume that this list represents the set of issues you would like to see addressed in Riot/Matrix for you to be wholly comfortable with its inclusion in privacytools' set of recommended services. I'll assume that they aren't all equally weighted, but I won't worry about relative priorities for now.

First up - the ones I can handle off the top of my head. These issues are part of the current privacy work:
- vector-im/riot-web#10161 - Store Integration Manager preferences in account data and allow user to change them somewhere sensible
- vector-im/riot-web#10167 - Present an aggregated terms of service dialogue at registration if possible
- vector-im/riot-web#10087 - Prompt to accept integration manager policies on registration
- vector-im/riot-web#10094 - Store identity server in Account Data and support choosing identity server integration in User Settings

As for open sourcing the scalar integration manager (vector-im/riot-web#7757 - Open source the integrations server WONTFIX) we have no plan to do this today, but we _are_ making it clearer and easier for users to control which Integrations Manager they use, and there's also Dimension which can be used as an open source alternative. Hopefully this mitigates our not having a plan to open source Scalar?

Some of the others weren't high on my agenda - I wouldn't want to consider exif stripping, private contact discovery and sticker encryption until we've got cross-signing working in Riot so that E2E encryption is _finally_ as user friendly as it needs to be. If they're blockers to your recommending or service, though, I can make sure that is at least kept in mind as we schedule future work.

The remaining items I'll have to check the status on tomorrow (it's gotten a little later than I planned). I'll be in touch ASAP with an update.

**Comment by Mikaela** [comment]
> In the interests of providing some hopefully useful feedback now, I'm going to assume that this list represents the set of issues you would like to see addressed in Riot/Matrix for you to be wholly comfortable with its inclusion in privacytools' set of recommended services. I'll assume that they aren't all equally weighted, but I won't worry about relative priorities for now.

You are correct, however I wouldn't consider some issues like the exif metadata scrubbing essential for listing Riot as as far as I am aware nothing else is doing that either. The ordering could be considered random as it's based on what I picked from other issues and then tried to search for issues based on other discussions, so towards the end it's in order of newest reported on your issue tracker.

> we are making it clearer and easier for users to control which Integrations Manager they use, and there's also Dimension which can be used as an open source alternative. Hopefully this mitigates our not having a plan to open source Scalar?

I find it acceptable, especially with open source alternative existing, as opposed to the current situation where an average user doesn't even know they are using Scalar. [my previous comment at prism-break](https://gitlab.com/prism-break/prism-break/issues/2176#note_190786462)

> Some of the others weren't high on my agenda

In my opinion the most important issue from those I listed would be actually removing removals (https://github.com/matrix-org/synapse/issues/1287) and allowing data to expire (https://github.com/matrix-org/matrix-doc/issues/447). (As you can see I started replying without reading your comment entirely at first)

There are also [the issues raised by muppeth](https://github.com/privacytoolsIO/privacytools.io/pull/562#issuecomment-457878353), do you have an issue number for them?

> The remaining items I'll have to check the status on tomorrow (it's gotten a little later than I planned). I'll be in touch ASAP with an update.

Thank you in advance and good night. I will try to sort the list better tomorrow.

**Comment by ggg27** [comment]
This is very interesting ( +1 )

Just to be clear, Synapse isn't the only way to implement Matrix.
There are also homeserver's like [Ruma](https://github.com/ruma/ruma).

Matrix is just a protocol, lots of ways to use it!

**Comment by Mikaela** [comment]
I think I got the list in a more clear order now.

* * * * *

> Just to be clear, Synapse isn't the only way to implement Matrix.
There are also homeserver's like Ruma.

Has Ruma had stable releases yet? While it could fix some issues with Synapse, I don't think it helps very much with some issues like https://github.com/matrix-org/synapse/issues/1287 while the federation includes Synapses that are doing that.

> Plus, you can always change your homeserver for most clients.

Yes, however identity server is currently not changeable after logging in (and yesterday I missed it entirely in login, if it even was there in RiotX) and currently integration server existing is not even told to the user being an option only a selfhoster can change.

**Comment by afonari** [comment]
ISs can and should be blocked if privacy is desired. IS is not needed for matrix chat client to function correctly (I think).

**Comment by afonari** [comment]
> Yes, however identity server is currently not changeable after logging in (and yesterday I missed it entirely in login, if it even was there in RiotX)

https://github.com/vector-im/riotX-android/issues/20

they don't want people to change it.

**Comment by Mikaela** [comment]
Thanks, there we have another issue to add to this tracking.

**Comment by ghbjklhv1** [comment]
I'm a [Fractal](https://wiki.gnome.org/Apps/Fractal) and [Weechat](https://matrix.org/docs/projects/client/weechat-matrix) fan. Although, I do use Riot.im for my aliases.

Although, I cannot confirm. But it seems like the allow you to change identity servers.

Edit: Also, what is `IS`?

**Comment by ghbjklhv1** [comment]
I know, many users dislike them; However, even Purism seems to have acknowledged web based apps are no longer a first priority: [https://archive.is/7nNkp](https://shop.puri.sm/librem-one-thanks/)

**Comment by lampholder** [comment]
> they don't want people to change it.

Hey - I just wanted to highlight that the ability to change Identity Servers after having logged in is on the roadmap for the current privacy sprint, across all clients. If you would like to see the plan and track its progress you can follow along here: https://vector-im.github.io/feature-dashboard/#/plan?label=privacy-sprint&repo=vector-im%2Friot-web&repo=vector-im%2Friot-ios&repo=vector-im%2Friot-android&repo=vector-im%2FriotX-android&repo=matrix-org%2Fmatrix-doc&repo=matrix-org%2Fsydent

(this tool just pulls issues with the same labels from across they myriad repos this work spans; you can find all the same stuff by searching each github repo manually).

**Comment by afonari** [comment]
> Edit: Also, what is `IS`?

identity server. Sorry shouldn't have written short right away.

>  to change Identity Servers after having logged

Why not at login? As it is now possible in the riot android (not riotx)?

**Comment by lampholder** [comment]
> Why not at login? As it is now possible in the riot android (not riotx)?

I'm hoping we can get rid of references to identity servers at login entirely, and just have them configured by the user in user settings after they've logged in (so identity server is a configurable property of the _account_, rather than the session).

Once the current work has landed, no data will be processed by any identity server until the user has explicitly accepted the terms and conditions, so from a data processing standing I think it's fine to drop it from registration/login. I think it feels a lot more natural from an average user's perspective, too.

This does present a slightly tricky UX problem of how we handle the idea of a 'default' identity server, though I think that's fine, too - default identity servers can be set at the client level or in the .well-known, and all that will mean is that the default identity server is the one that your client will prompt you to accept the terms and conditions of if and when you try and do something identity-servery (e.g. invite by email or publicly link your mxid with your email).

We might want to maintain separate identity server choice states for this - i.e. "don't use an identity server" as distinct from "this is the identity server I would use, but I won't send it any data because I haven't accepted its terms and conditions". Even though they're materially the same (from a data processing perspective), it would be nice for people to feel like they're not at risk of _accidentally_ accepting the terms and conditions of an identity server they don't want to use.

**Comment by lampholder** [comment]
Hi all,

I've updated some of the relevant issues to get them into our [privacy project tracking tool](https://vector-im.github.io/feature-dashboard/#/plan?label=privacy-sprint&repo=vector-im%2Friot-web&repo=vector-im%2Friot-ios&repo=vector-im%2Friot-android&repo=vector-im%2FriotX-android&repo=matrix-org%2Fmatrix-doc&repo=matrix-org%2Fsydent). I've tried to summarise clearly:

### Things which have been added to the plan:

- https://github.com/matrix-org/synapse/issues/1287, https://github.com/matrix-org/synapse/issues/4565 and https://github.com/matrix-org/synapse/issues/1263 have been added to `phase:1`
- https://github.com/matrix-org/matrix-doc/issues/447 has been added to `phase:2` - this is not to assign it lower priority than the other issues, rather it is to say that there are more hurdles to completing this (getting the MSC agreed primarily) so we're not exactly sure when it will land

### Issues from your list which I think are mitigated by other issues:

- https://github.com/vector-im/riot-web/issues/7649 is being addressed by https://github.com/matrix-org/matrix-doc/pull/2134
- https://github.com/vector-im/riotX-android/issues/20 there's been some discussion on that issue - RiotX doesn't support interacting with an Identity Server yet (or an integration server for that matter); there is a reference to vector.im in the codebase, though - https://github.com/vector-im/riotX-android/pull/446 has been filed to address this though from @maxidorius' comments it sounds like there may be a bit more to do

### Things which haven't been added to the plan:
- https://github.com/matrix-org/matrix-doc/issues/1228 - even though we're very keen to fix this, we can't commit to it right now since it's a large and invasive change; we need to weigh it against the other objectives we're trying to achieve. If privacytools aren't comfortable recommending matrix whilst matrix IDs are baked into events, could this be mitigated by recommending users choose non-identifying IDs?
- https://github.com/matrix-org/synapse/issues/1941 is relatively easy to implement, but doesn't add a lot of value until https://github.com/matrix-org/matrix-doc/issues/1228 lands
- matrix-org/matrix.org#342  - we rely on Cloudflare for DoS mitigation - matrix.org can only stay online thanks to this service. If this is a hard blocker for a privacytools recommendation then I understand, though are you are able to recommend alternative homeservers/self hosting instead? 
- https://github.com/vector-im/riot-web/issues/4426 - there's no plan to do this at this stage (users _can_ strip their own exif data before sharing, which is not great I know - if anyone is willing to provide a PR for this it would be warmly received)
- https://github.com/vector-im/riot-meta/issues/287 - we've no plans to make any tor-specific changes at this stage, though Riot Web mostly works fine in tor browser if that's of any value. Once again, though, community-provided PRs for this would be warmly received

**Comment by Mikaela** [comment]
Thanks for the update,

> vector-im/riot-web#7649 is being addressed by matrix-org/matrix-doc#2134

I added matrix-org/matrix-doc#2134 with a slash.

> If this is a hard blocker for a privacytools recommendation then I understand, though are you are able to recommend alternative homeservers/self hosting instead?

I am not sure as I don't think anyone (in the team or commenting actively) is checking for Cloudflared domains and in #1054 (ICANNnet DNS servers) half of the suggestions are using Cloudflare. I think a bigger issue would be Riot not exposing the default homeserver matrix.org by default, do you have an issue tracking it? From that issue I also get impression that you have a wish to shut down Matrix.org homeserver (https://github.com/matrix-org/matrix.org/issues/342#issuecomment-468958754) which I imagine would resolve these issues unless you would replace it with another homeserver that is suggested by default unless the user knows to click advanced/additional/similar settings.

Personally my main concerns with Cloudflare is

> I understand this to mean that Cloudflare can one way or another read all traffic going through Matrix.org including IRC users who have never even heard of Matrix if someone happens to use Matrix on the same IRC channel? Matrix.org is quite big compared to an individual Cloudflaring their IRC client, I have heard a number 1500 connections associated with a I-line request from third party bridge admin.

**Comment by lampholder** [comment]
> I think a bigger issue would be Riot not exposing the default homeserver matrix.org by default, do you have an issue tracking it?

I think there might be crossed wires here - the queued up privacy work has a few items to better highlight the default identity server and integration manager, but the default homeserver is already pretty well highlighted:

![image](https://user-images.githubusercontent.com/1922197/62135878-ec627180-b2da-11e9-8e51-9aa56adb800c.png)

and

<img width="216" alt="image" src="https://user-images.githubusercontent.com/1922197/62135961-1a47b600-b2db-11e9-8fe9-ad38af2d8ba9.png">

Or do you mean Riot's not highlighting that the default homeserver is behind cloudflare?

**Comment by Mikaela** [comment]
Your screenshots look good to me (other than not mentioning the identity server), but they seem to be from Riot Desktop, while the currently recommended Riot Android app looks like this:

![Riot Android screenshot](https://chat.privacytools.io/_matrix/media/r0/download/privacytools.io/JmIFqgeODzVSHlpqFBFfRKBi)

I have misremembered or am thinking of older version which had advanced settings while currently there is "edit server settings" and I don't see matrix.org/vector.im mentioned without checking it, even if I click login.

I am currently not able to get Riot X login screen as I don't want to regenerate keys yet again.

**Comment by lampholder** [comment]
Oh, yes - I'm Delivery Manager for Riot Web, so I sometimes have something of a Riot Web bias, sorry.

It would be better if the mobile apps made it clearer you were logging into/registering on matrix.org, though of course users registering on matrix.org will be sent past the matrix.org terms and conditions before that registration is completed.

I'll make an issue for this, too.

**Comment by lampholder** [comment]
> I am currently not able to get Riot X login screen as I don't want to regenerate keys yet again.

Key backup works on Riot X, so you could back your keys up to save regenerating. The backups are encrypted locally and stored on the homeserver encrypted (without the homeserver ever having access to the encryption key).

**Comment by Mikaela** [comment]
> I'll make an issue for this, too.

Please give the link here when you are done.

> Key backup works on Riot X, so you could back your keys up to save regenerating. The backups are encrypted locally and stored on the homeserver encrypted (without the homeserver ever having access to the encryption key).

Doesn't this however give me a separate device ID and fingerprint that I would need to reverify with people again?

**Comment by afonari** [comment]
bq. I have misremembered or am thinking of older version which had advanced settings while currently there is "edit server settings" and I don't see matrix.org/vector.im mentioned without checking it, even if I click login.

This is fixed https://github.com/LiMium/mini-vector-android (https://github.com/LiMium/mini-vector-android/pull/27) Custom options is checked by default and Identity server set to localhost.

**Comment by ara4n** [comment]
> > Yes, however identity server is currently not changeable after logging in (and yesterday I missed it entirely in login, if it even was there in RiotX)
> 
> [vector-im/riotX-android#20](https://github.com/vector-im/riotX-android/issues/20)
> 
> they don't want people to change it.

@afonari There is massive confusion about this - the reason RiotX didn't expose UI for configuring the identity server is that it does not implement any identity functionality(!)  The default setting was hanging around the codebase unused, and got removed in https://github.com/vector-im/riotX-android/pull/446.

**Comment by afonari** [comment]
@ara4n This is great news, thanks! Hopefully, if it is added back, it will be chageable from GUI.

**Comment by ara4n** [comment]
of course! this has always been the plan.

**Comment by lampholder** [comment]
> Please give the link here when you are done.

Riot iOS: https://github.com/vector-im/riot-ios/issues/2614
RiotX: https://github.com/vector-im/riotX-android/issues/450 (issue already closed, RiotX actually shows the default homeserver already)
Riot Android: https://github.com/vector-im/riot-android/issues/3238 - not sure we'll actually want to make the changes to Riot Android - it depends how quickly we can replace Riot Android with RiotX.

> Doesn't this however give me a separate device ID and fingerprint that I would need to reverify with people again?

Sorry, yes it does. As an aside, cross signing will solve this problem and is very much inbound - the backend support is basically complete (but there's still a lot of UX to do yet).

**Comment by BearerOfHonesty** [comment]
> vector-im/riot-web#4426 - riot does not scrub exif data from upload
> 
>     I don't think anything else does this either, please correct me.
> 

Discord does or used to do this.

**Comment by afonari** [comment]
https://github.com/LiMium/mini-vector-android/pull/32 was merged into mini-vector for android. I think this removes all the integrations. @maxidorius based on your research are there any other "hidden" integrations in the riot-android?

**Comment by maxidorius** [comment]
@afonari There are others like the Integration manager. I didn't dig into android specifically, but from network activity I saw, the identity server is the tip of the iceberg, as being the only configurable item.

**Comment by afonari** [comment]
Max, they exposed quite a few in the config.xml: https://github.com/vector-im/riot-android/blob/develop/vector/src/main/res/values/config.xml

I searched for "vector.im" in the riot-android repo, I couldn't find anything that it is leaking except those from the config.xml.

**Comment by ara4n** [comment]
See https://matrix.org/blog/2019/09/27/privacy-improvements-in-synapse-1-4-and-riot-1-4, which solves many of the issues touched on in the OP.

**Comment by afonari** [comment]
@ara4n I can still reproduce https://github.com/privacytoolsIO/privacytools.io/issues/1338 with Riot-web 1.4. My config is:
```
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://chat.privacytools.io",
            "server_name": "chat.privacytools.io"
        },
        "m.identity_server": {
            "base_url": "https://chat.privacytools.io"
        }
    },
    "disable_custom_urls": false,
    "disable_guests": false,
    "disable_login_language_selector": false,
    "disable_3pid_login": false,
    "brand": "Riot",
    "integrations_ui_url": "https://chat.privacytools.io/",
    "integrations_rest_url": "https://chat.privacytools.io/api",
    "integrations_widgets_urls": [
        "https://chat.privacytools.io/_matrix/integrations/v1"
    ],
    "integrations_jitsi_widget_url": "https://chat.privacytools.io/api/widgets/jitsi.html",
    "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
    "defaultCountryCode": "GB",
    "showLabsSettings": false,
    "features": {
        "feature_pinning": "labs",
        "feature_custom_status": "labs",
        "feature_custom_tags": "labs",
        "feature_state_counters": "labs"
    },
    "default_federate": true,
    "default_theme": "light",
    "roomDirectory": {
        "servers": [
            "matrix.org"
        ]
    },
    "welcomeUserId": false,
    "piwik": false,
    "enable_presence_by_hs_url": {
        "https://matrix.org": false
    }
}
```

**Comment by afonari** [comment]
@jryans can you please clarify. When I add an email address from riot web 1.4 running on localhost with HS pointing to somehost1.org and IS pointing to somehost2.org, where does this request go?

**Comment by jryans** [comment]
> @jryans can you please clarify. When I add an email address from riot web 1.4 running on localhost with HS pointing to somehost1.org and IS pointing to somehost2.org, where does this request go?

Riot 1.4 behaves differently when adding an email to your HS account depending on whether the HS supports the new privacy changes, currently part of Synapse 1.4.

If your HS is older (without privacy work), then Riot passes the selected IS to the HS and the HS talks to IS on your behalf to trigger the email.

If your HS includes privacy work (such as Synapse 1.4), then the IS is not involved at all. The HS handles email validation internally (or chooses to delegate email sending elsewhere and should be explained in the privacy policy of that HS).

**Comment by afonari** [comment]
> If your HS is older (without privacy work), then Riot passes the selected IS to the HS and the HS talks to IS on your behalf to trigger the email.

Yes, I can see that:
https://chat.privacytools.io/_matrix/client/r0/account/3pid/email/requestToken

What I don't understand is, how it is possible for IS to send email if IS is set to localhost (non existent IS, which is confirmed by the yellow warning at the login page). IS is set using:
```
"m.identity_server": {
            "base_url": "localhost"
        }
```

**Comment by afonari** [comment]
@jryans thanks for the explanations.

**Comment by afonari** [comment]
Linking another privacy case: https://github.com/vector-im/riot-web/issues/10696

**Comment by maxidorius** [comment]
@JonahAragon Recent changes in Riot code regarding auto-discovery made this quite complex. I would be very cautious with any approach you take and be sure to test it before hand.

**Comment by PopeRigby** [comment]
Why was this closed, @Mikaela? Are all the problems fixed?

**Comment by Mikaela** [comment]
> Why was this closed, @Mikaela? Are all the problems fixed?

 because @JonahAragon thought in #1392 (which dngray and I approved before I merged it) that it/relisting resolves this issue. For the discussion resulting me to approve in the end, see https://github.com/privacytoolsIO/privacytools.io/issues/1389.

I am content with leaving this closed as there is that upstream privacy tracker and I am not following everything happening there and don't have the capability of keeping this up-to-date, and would consider https://github.com/privacytoolsIO/privacytools.io/issues/1395 as the successor.

**Comment by afonari** [comment]
I agree with @PopeRigby, I think this should stay open. There are many unresolved issues.

**Comment by afonari** [comment]
One important issue is https://github.com/vector-im/riot-web/issues/10696: Allow users to disconnect from an integration manager entirely in the same way that we support doing this for identity servers.

**Comment by Mikaela** [comment]
@privacytoolsIO/editorial Are there volunteers on keeping this up-to-date?

I will move that to #1395, while another option would be to not use Riot as I think it's the only client that implements an integration manager.

**Comment by afonari** [comment]
> @privacytoolsIO/editorial Are there volunteers on keeping this up-to-date?

I'm OK posting here links to cases and following this thread.

**Comment by JonahAragon** [comment]
FYI the default on our Riot install is now an integration manager that is 1) controlled by me, and 2) disabled by default until you specifically use it once and check an agreement box.

**Comment by Mikaela** [comment]
Is there more documentation about it somewhere and what is the address that can be given to Riot user settings?
