### ISSUE TITLE
[META] Browser extensions issues

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1328]
* [ ] https://github.com/privacytoolsIO/privacytools.io/issues/1292 - Suggest HTTPS Everywhere EASE mode and note that many extensions may conflict due to CSP handling in Firefox
* [ ] https://github.com/privacytoolsIO/privacytools.io/issues/1326 - Decentraleyes needs additional configuration when used together with HTTPS Everywhere (on Chromium) or a lot of other content blockers on any browser
* [ ] https://github.com/privacytoolsIO/privacytools.io/issues/1327 - Browser addons needs more categories

**Comment by jasonbrown1965** [comment]
Minor update for add-ons page:

Step 2 under about:config **Preparations** currently reads:
_2. Press the button "I'll be careful, I promise!"_

In FF 70.01, the text now reads:
"I accept the risk!"

**Comment by dngray** [comment]
I'm thinking we should add [Temporary Containers](https://github.com/stoically/temporary-containers) and link to [this article](https://medium.com/@stoically/enhance-your-privacy-in-firefox-with-temporary-containers-33925cd6cd21) under the power user section. Mention that Cookie Autodelete is not necessary when using.

I also think [CleanURLs](https://addons.mozilla.org/firefox/addon/clearurls/) is certainly worth adding, typically as people make the mistake of pasting URLs they've visited with those tracking parameters on them.

For the uMatrix description we should describe that you don't need NoScript in addition to uMatrix, if you configure uMatrix to [How to block 1st party scripts everywhere by default](https://github.com/gorhill/uMatrix/wiki/How-to-block-1st-party-scripts-everywhere-by-default).

We should also mention for Decentraleyes that [might need further configuration](https://git.synz.io/Synzvato/decentraleyes/-/wikis/Frequently-Asked-Questions#for-umatrix-and-ublock-origin-non-easy-mode-users) if used in conjunction with uMatrix or uBlock.

**Comment by Mikaela** [comment]
> We should also mention for Decentraleyes that might need further configuration if used in conjunction with uMatrix or uBlock.

Alternatively we could consider delisting Decentraleyes?

* https://forum.privacytools.io/t/discussion-decentraleyes/269/8?u=mikaela

**Comment by dngray** [comment]
Likely LocalCDN requires the same kind of configuration.

**Comment by Mikaela** [comment]
Yes, and it appears that since I previously looked into it (in the forum), LocalCDN has added a generator for what to put into µMatrix/µBlock configuration.

* https://gitlab.com/nobody42/localcdn/-/wikis/Rule-sets-for-uMatrix-and-uBlock-Origin-users

My suggestion/intent was to delist Decentraleyes without replacing it, but I guess now LocalCDN could be worth considering.

**Comment by dngray** [comment]
Requires investigation: https://github.com/privacytoolsIO/privacytools.io/issues/1801

**Comment by dngray** [comment]
Also related https://github.com/privacytoolsIO/privacytools.io/issues/927

**Comment by dngray** [comment]
I think we we should just remove localcdn/decentraleyes and encourage first party isolation https://github.com/privacytools/privacytools.io/pull/1931#issuecomment-703383509

I think cookie autodelete should also be removed, as it doesn't actually work on Fenix.
