### ISSUE TITLE
🆕 Software Suggestion | NameCoin

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1492]
## Basic Information

**Name:** NameCoin
**Category:** DNS? (Blocked by: https://github.com/privacytoolsIO/privacytools.io/pull/1372 & https://github.com/privacytoolsIO/privacytools.io/issues/1466) ?
**URL:** https://www.namecoin.org/

## Description

It was previously removed due to some concerns that were not correct and they are addressing valid concerns. See discussion starting from https://github.com/privacytoolsIO/privacytools.io/pull/1273#issuecomment-553746882.

## TODO

* [ ] getting the blockers in category handled as currently the DNS section is moving towards ICANN-encrypted-DNS only and NameCoin only advices DNSSEC-trigger at the moment (the best case here would probably be if they started recommending encrypted ICANN DNS?)
     * I wonder if DNSSEC-Trigger would be open for enabling DoT, as it's based on Unbound, but I have no idea if it does opportunistic DoT and I think enabling a hardcoded DNS server would be a good idea.
* Personally I should look into @JeremyRand 's talks at 34C3 and 35C3
* [ ] looking through their documentation and ensuring they don't have suggestions for using NameCoin domains without their software
    * [ ] maybe even adding a warning with the relisting to not do that quoting them on it?
* [ ] hopefully indepedently confirming they are doing what they say (I am not the person for this).

*Assigning myself as I was the one to suggest removal and opened the PR, but please feel free to work on this and no time promises etc.*

**Comment by Mikaela** [comment]
I was confused by not seeing a forum thread for NameCoin, but apparently it was worth mentioning while I was writing everything with an assumption that it will be a recommended DNS tool, so I may have strictened the criteria a bit.

Do we want to call it as worth mentioning or see if #1466 will bring an opportunity to list it as recommended somewhere? We are currently missing non-ICANN DNS section and I think NameCoin is the most established candidate for that role (and I am yet to hear anything from https://github.com/opennic/opennic-web/issues/68) while excluding Tor and I2P (self-contained networks, which NameCoin AFAIK doesn't do, but would that be a good place for worth mentioning?).

There would also be some P2P DNS attempts, but I think I have encountered three different projects calling themselves as e.g. PeerDNS, so I wouldn't be open for recommending any of them as more than worth mentioning.

**Comment by JeremyRand** [comment]
Coincidentally, I noticed some unacceptable wording on the r/Namecoin subreddit's description (which AFAIK predates the Namecoin developers' control of that subreddit); I've filed an issue for getting it fixed.  Feel free to chime in on [that issue](https://github.com/namecoin/namecoin.org/issues/480#issuecomment-554579016) if you have any comments on the proposed fix.

**Comment by JeremyRand** [comment]
> I guess I may be thinking of https://bit.namecoin.org/browse.html listing "Volunteer-Run DNS Servers" and while it says "For quick testing" and "Using this for everyday browsing or anything sensitive is strongly discouraged...", I fear listing it as an option may send the wrong signal ("If I am not doing anything special, I don't need to do this") and I don't know how much people using NameCoin domains or third party DNS servers perform research and if they ever hear that their favourite DNS server is not recommended.

I figured out why that text was still there without me knowing about it.  The page in question was migrated to https://www.namecoin.org/dot-bit/browsing-instructions/ a while back, and subsequently I had that section of the page removed.  But it looks like we neglected to replace the old URL with a redirect, and there seem to still be some pages on our site that link to the old URL.  I've filed an issue about fixing this.  Thanks again for pointing that out.
