### ISSUE TITLE
Add Onion links for websites that offer it.

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#190]
Here's an (incomplete?) list:

**TODO** (checked = in progress):

- [x] [Tor Browser](https://www.privacytools.io/#browser) : http://expyuzz4wqqyqhjn.onion/

- [x] [ProtonMail](https://www.privacytools.io/#email) :  https://protonirockerxow.onion/ (in  #166)

- [x] [searx.me](https://www.privacytools.io/#search) :  http://ulrn6sryqaifefld.onion/

- [x] [OnionShare](https://www.privacytools.io/#filesharing) : http://elx57ue5uyfplgva.onion/

- [x] [Qubes OS](https://www.privacytools.io/#os) : http://qubesos4rrrrz6n4.onion/

- [x] [Debian](https://www.privacytools.io/#os) : http://sejnfjrq6szgca7v.onion/

- [x] [Whonix](https://www.privacytools.io/#os) : http://kkkkkkkkkk63ava6.onion (in #189)

- [x] [zcash](https://www.privacytools.io/#cryptocurrency) : http://zcashph5mxqjjby2.onion

**POTENTIAL:**

- [x] [DuckDuckGo](https://www.privacytools.io/#search) ([PR](https://github.com/privacytoolsIO/privacytools.io/pull/157)) : https://3g2upl4pq6kufc4m.onion/

**DONE:**

**Comment by kewde** [comment]
Good idea I really like this.
If possible, could we put the qubes os one in with #189 ?

**Comment by e5f3c2ea895af0f27667** [comment]
>  If possible, could we put the Qubes OS and OnionShare ones in with https://github.com/privacytoolsIO/privacytools.io/pull/189 ?

I prefer that we leave that for another PR. We shouldn't include the full onion URL (especially considering that next-gen onion services will have 52 characters in their address), but rather have an onion icon adjacent to the website button that links to the onion address. What do you think?

**Comment by e5f3c2ea895af0f27667** [comment]
I'm in no way a designer, but this is what I was thinking about: 

![](https://s11.postimg.org/41jc18qvn/Untitled.png)

**Comment by kewde** [comment]
Added zcash onion url

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
If I remember correctly, 0bin also have an onion service, can't find it tho

**Comment by Shifterovich** [comment]
0bin is JS-based. Found an onion URL, but not sure whether official.
